name: Hardware CI

on:
  push:
    branches: [ "dev", "main" ]
  workflow_dispatch:
  schedule:
    # Daily 02:20 America/Chicago ≈ 08:20 UTC (adjust as desired)
    - cron: "20 8 * * *"

permissions:
  contents: read
  packages: write

jobs:
  build_arm64_hosted:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Build (ARM64 hosted runner, no hardware)
        run: |
          docker version
          docker build .

  build_and_push_multiarch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push multi-arch image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/rtl-haos:${{ github.sha }}
          docker buildx build             --platform linux/amd64,linux/arm64,linux/arm/v7             -t $IMAGE             --push             .

  hardware_smoke:
    # Hardware-in-the-loop: run only when explicitly requested (manual) or on the schedule.
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    continue-on-error: true
    needs: build_and_push_multiarch
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: pi5_arm64
            runs_on: [self-hosted, linux, pi5, sdr]
          - name: pi3_armv7
            runs_on: [self-hosted, linux, pi3, sdr]
    runs-on: ${{ matrix.runs_on }}
    concurrency:
      group: hw-${{ matrix.name }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - name: Host sanity (runner)
        run: |
          ./.github/scripts/host_sanity.sh

      - name: Pull image built for this arch
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/rtl-haos:${{ github.sha }}
          docker pull $IMAGE

      - name: Hardware smoke (open dongle)
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/rtl-haos:${{ github.sha }}
          docker run --rm --privileged             -v /dev/bus/usb:/dev/bus/usb             $IMAGE /bin/sh -lc '/app/.github/scripts/sdr_smoke.sh'

      - name: Hardware smoke (rtl_433 JSON startup)
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/rtl-haos:${{ github.sha }}
          docker run --rm --privileged             -v /dev/bus/usb:/dev/bus/usb             $IMAGE /bin/sh -lc '/app/.github/scripts/rtl433_json_smoke.sh'

      - name: Hardware smoke (stream/dropout check)
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/rtl-haos:${{ github.sha }}
          docker run --rm --privileged             -v /dev/bus/usb:/dev/bus/usb             $IMAGE /bin/sh -lc '/app/.github/scripts/sdr_stream_test.sh'

      - name: Diagnostics on failure
        if: failure()
        run: |
          echo "[DIAG] lsusb:"
          (lsusb || true)
          echo "[DIAG] dmesg (last 120 lines):"
          (dmesg | tail -120 || true)
